import {
  buildFallbackItinerary,
  buildKeywordSearchPlan,
  buildKtoDirectItinerary,
  buildKtoEnnoiaItinerary,
  parseAgentPayload,
  selectRoute,
} from "./index.ts";
import type { ItineraryRequest, KtoCandidate } from "./index.ts";

Deno.test("keyword plan expands user interests into Korean searches", () => {
  const searches = buildKeywordSearchPlan(
    request("Myeongdong, Seoul", "Palace, Hanok village, Traditional market"),
  );
  const keywords = searches.map((search) => search.keyword);

  assert(keywords.includes("경복궁"));
  assert(keywords.includes("북촌한옥마을"));
  assert(keywords.includes("광장시장"));
  assert(keywords.includes("명동"));
});

Deno.test("different preference sets select different five-stop routes", () => {
  const cases = [
    request("Myeongdong, Seoul", "Palace, Hanok village, Traditional market"),
    request("Hongdae, Seoul", "Shopping, K-pop, Cafe"),
    request("Seoul Station, Seoul", "Nature, Museum, Quiet", "Solo", "Quiet"),
    request("Jongno, Seoul", "Local food, Traditional market"),
    request("Gangnam, Seoul", "Night view, Couple", "Couple", "Moderate"),
  ];

  const signatures = cases.map((item) => {
    const route = selectRoute(candidatePool, item);
    assertEquals(route.length, 5);
    assertEquals(new Set(route.map((candidate) => candidate.contentid)).size, 5);
    return route.map((candidate) => candidate.contentid).join("|");
  });

  assert(new Set(signatures).size > 1, "routes should vary by preference input");
});

Deno.test("parses ennoia string content JSON", () => {
  const payload = ennoiaPayload();
  const parsed = parseAgentPayload(JSON.stringify({
    choices: [{ message: { content: JSON.stringify(payload) } }],
  }));

  assert(parsed);
  assertEquals(readItems(parsed).length, 5);
  assertEquals(readItems(parsed)[0].place_name, "Deoksugung Daehanmun");
});

Deno.test("parses ennoia array content text parts", () => {
  const payload = ennoiaPayload();
  const json = JSON.stringify(payload);
  const parsed = parseAgentPayload(JSON.stringify({
    data: {
      choices: [
        {
          message: {
            content: [
              { type: "text", text: json.slice(0, 40) },
              { type: "text", text: json.slice(40) },
            ],
          },
        },
      ],
    },
  }));

  assert(parsed);
  assertEquals(readItems(parsed)[0].kto_content_id, "1605981");
});

Deno.test("strips markdown JSON fences", () => {
  const parsed = parseAgentPayload(JSON.stringify({
    data: {
      output_text: `\`\`\`json\n${JSON.stringify(ennoiaPayload())}\n\`\`\``,
    },
  }));

  assert(parsed);
  assertEquals(readItems(parsed).length, 5);
});

Deno.test("extracts JSON object from minor surrounding prose", () => {
  const parsed = parseAgentPayload(JSON.stringify({
    data: {
      message: {
        content:
          `Here is the itinerary.\n${JSON.stringify(ennoiaPayload())}\nDone.`,
      },
    },
  }));

  assert(parsed);
  assertEquals(readItems(parsed)[0].place_name, "Deoksugung Daehanmun");
});

Deno.test("ennoia success sets source_type to kto_openapi_ennoia", () => {
  const response = buildKtoEnnoiaItinerary(
    request("Myeongdong, Seoul", "Palace, Hanok village, Traditional market"),
    candidateRoute,
    candidateRoute.length,
    ennoiaPayload(),
  );

  assertEquals(response.source_type, "kto_openapi_ennoia");
  assertEquals(response.source_badge, "KTO OpenAPI + ennoia");
  assertEquals(readItems(response).length, 5);
});

Deno.test("ennoia failure with KTO success sets source_type to kto_openapi_basic", () => {
  const response = buildKtoDirectItinerary(
    request("Myeongdong, Seoul", "Palace, Hanok village, Traditional market"),
    candidateRoute,
    candidateRoute.length,
    { ennoia_error_code: "ennoia_parse_error" },
  );

  assertEquals(response.source_type, "kto_openapi_basic");
  assertEquals(response.source_badge, "KTO OpenAPI");
  assertEquals(response.ennoia_error_code, "ennoia_parse_error");
  assertEquals(
    response.source_note,
    "KTO OpenAPI data succeeded; ennoia generation failed and basic descriptions were generated by the backend.",
  );
});

Deno.test("fallback KTO data sets source_type to kto_openapi_fallback", () => {
  const response = buildFallbackItinerary(
    request("Myeongdong, Seoul", "Palace, Hanok village, Traditional market"),
    "KTO OpenAPI returned fewer than 5 usable candidates",
  );

  assertEquals(response.source_type, "kto_openapi_fallback");
  assertEquals(response.source_badge, "Demo fallback");
});

function request(
  baseLocation: string,
  interests: string,
  companionType = "Solo",
  crowdPreference = "Quiet to Moderate",
): ItineraryRequest {
  return {
    user_language: "English",
    trip_days: "1",
    base_location: baseLocation,
    travel_date: "May 18, Sun",
    interests,
    companion_type: companionType,
    crowd_preference: crowdPreference,
  };
}

function ennoiaPayload(): Record<string, unknown> {
  return {
    title: "Palace and hanok route",
    summary: "Five KTO-backed stops.",
    estimated_time_saved: "1h 10m",
    items: candidateRoute.map((item, index) => ({
      order: index + 1,
      time: ["09:00", "11:00", "13:00", "15:30", "18:30"][index],
      place_name: item.title,
      kto_content_id: item.contentid,
      reason: "Selected from KTO data.",
      culture_tip: "Use an empty string if unknown.",
      stay_time: "Stay 1h",
      crowd_level: "low",
    })),
  };
}

function readItems(payload: Record<string, unknown>): Record<string, unknown>[] {
  return Array.isArray(payload.items)
    ? payload.items.filter((item): item is Record<string, unknown> =>
      typeof item === "object" && item !== null && !Array.isArray(item)
    )
    : [];
}

const candidateRoute: KtoCandidate[] = [
  candidate("Deoksugung Daehanmun", "1605981", "12", "Seoul Jung-gu", "Palace", 126.976, 37.566),
  candidate("Hanboknam Gyeongbokgung", "2390314", "38", "Seoul Jongno-gu", "Hanok village", 126.977, 37.578),
  candidate("Gwangjang Market", "132183", "38", "Seoul Jongno-gu", "Traditional market", 127.001, 37.57),
  candidate("Namsangol Hanok Village", "126747", "12", "Seoul Jung-gu", "Hanok village", 126.994, 37.559),
  candidate("Bukchon Hanok Village", "126537", "12", "Seoul Jongno-gu", "Hanok village", 126.984, 37.582),
];

const candidatePool: KtoCandidate[] = [
  candidate("경복궁", "1001", "12", "서울 종로구 사직로", "Palace", 126.977, 37.579),
  candidate("창덕궁", "1002", "12", "서울 종로구 율곡로", "Palace", 126.991, 37.579),
  candidate("북촌한옥마을", "2001", "12", "서울 종로구 계동길", "Hanok village", 126.984, 37.582),
  candidate("익선동 한옥거리", "2002", "12", "서울 종로구 수표로", "Hanok village", 126.99, 37.573),
  candidate("광장시장", "3001", "38", "서울 종로구 창경궁로", "Traditional market", 127.001, 37.57),
  candidate("망원시장", "3002", "38", "서울 마포구 포은로", "Traditional market", 126.906, 37.556),
  candidate("성수 카페거리", "4001", "39", "서울 성동구 성수이로", "Cafe", 127.054, 37.543),
  candidate("연남동 카페", "4002", "39", "서울 마포구 동교로", "Cafe", 126.923, 37.562),
  candidate("홍대거리", "5001", "12", "서울 마포구 홍익로", "K-pop", 126.923, 37.557),
  candidate("명동거리", "6001", "38", "서울 중구 명동길", "Shopping", 126.985, 37.563),
  candidate("더현대 서울", "6002", "38", "서울 영등포구 여의대로", "Shopping", 126.929, 37.526),
  candidate("국립중앙박물관", "7001", "14", "서울 용산구 서빙고로", "Museum", 126.98, 37.523),
  candidate("서울역사박물관", "7002", "14", "서울 종로구 새문안로", "Museum", 126.971, 37.57),
  candidate("서울숲", "8001", "12", "서울 성동구 뚝섬로", "Nature", 127.037, 37.544),
  candidate("한강공원", "8002", "12", "서울 영등포구 여의동로", "Nature", 126.934, 37.528),
  candidate("남산서울타워", "9001", "12", "서울 용산구 남산공원길", "Night view", 126.988, 37.551),
  candidate("반포한강공원", "9002", "12", "서울 서초구 신반포로", "Couple", 126.995, 37.51),
  candidate("을지로 노포거리", "9101", "39", "서울 중구 을지로", "Local food", 126.991, 37.566),
  candidate("종로 맛집거리", "9102", "39", "서울 종로구 종로", "Local food", 126.991, 37.571),
];

function candidate(
  title: string,
  contentid: string,
  contenttypeid: string,
  addr1: string,
  interest: string,
  mapx: number,
  mapy: number,
): KtoCandidate {
  return {
    title,
    contentid,
    contenttypeid,
    addr1,
    firstimage: "https://example.com/image.jpg",
    mapx,
    mapy,
    matched_interest: interest,
    matched_interests: [interest],
    matched_keywords: [title],
    candidate_score: 0,
    category: interest.toLowerCase().replaceAll(" ", "_"),
    area_key: addr1.split(" ").slice(0, 2).join(" "),
  };
}

function assert(value: unknown, message = "assertion failed"): asserts value {
  if (!value) throw new Error(message);
}

function assertEquals<T>(actual: T, expected: T, message?: string): void {
  if (actual !== expected) {
    throw new Error(message ?? `expected ${expected}, got ${actual}`);
  }
}
