type ItineraryRequest = {
  user_language: string;
  trip_days: string;
  base_location: string;
  travel_date: string;
  interests: string;
  companion_type: string;
  crowd_preference: string;
};

type JsonMap = Record<string, unknown>;

type EnnoiaSecrets = {
  endpoint: string;
  project: string;
  apiKey: string;
  hash: string;
  userId: string;
};

type PersistenceResult = {
  saved: boolean;
  table: "itinerary_plans";
  id?: string;
  error?: string;
};

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const requiredFields: Array<keyof ItineraryRequest> = [
  "user_language",
  "trip_days",
  "base_location",
  "travel_date",
  "interests",
  "companion_type",
  "crowd_preference",
];

const persistedSourceType = "ennoia_kto_mcp";
const sourceNote =
  "Generated by ennoia Agent through Korea Tourism Organization MCP data.";

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed." }, 405);
  }

  const bodyResult = await readJsonBody(request);
  if (!bodyResult.ok) {
    return jsonResponse({ error: bodyResult.error }, 400);
  }

  const validationError = validateFields(bodyResult.body, requiredFields);
  if (validationError) {
    return jsonResponse({ error: validationError }, 400);
  }

  const secrets = readEnnoiaSecrets();
  if (!secrets.ok) {
    return jsonResponse(
      {
        error:
          `Missing Edge Function secrets: ${secrets.missing.join(", ")}.`,
      },
      500,
    );
  }

  const params = bodyResult.body as ItineraryRequest;
  const ennoiaPayload = {
    hash: secrets.value.hash,
    params,
    messages: [
      {
        role: "user",
        content:
          "Use Korea Tourism Organization MCP to recommend a one-day Seoul itinerary. Return valid JSON only. The JSON must include id, dateLabel, title, estimatedTimeSaved, sourceNote, and exactly 5 items. Each item must include id, order, time, placeName, crowdLevel, stayTime, aiTip, kto_content_id, mapX, and mapY. Choose KTO places that have content IDs; do not return placeholders.",
      },
    ],
  };

  try {
    const ennoiaResponse = await fetch(secrets.value.endpoint, {
      method: "POST",
      headers: {
        project: secrets.value.project,
        apiKey: secrets.value.apiKey,
        "X-ENNOIA-USER-ID": secrets.value.userId,
        "Content-Type": "application/json; charset=utf-8",
      },
      body: JSON.stringify(ennoiaPayload),
    });

    const responseText = await ennoiaResponse.text();
    if (!ennoiaResponse.ok) {
      return jsonResponse(
        {
          error: "ennoia Agent request failed.",
          status: ennoiaResponse.status,
          detail: safeJsonOrText(responseText),
        },
        ennoiaResponse.status,
      );
    }

    const decoded = parseJsonText(responseText);
    const payload = withSourceMetadata(extractAgentPayload(decoded));
    const payloadError = validateItineraryPayload(payload);
    if (payloadError) {
      return jsonResponse({ error: payloadError }, 502);
    }

    const persistence = await persistItineraryPlan(params, payload);

    return jsonResponse(
      {
        ...payload,
        persistence,
        persisted: persistence.saved,
        persistedPlanId: persistence.id,
      },
      200,
    );
  } catch (error) {
    console.error(
      "ennoia itinerary request failed",
      error instanceof Error ? error.message : "unknown error",
    );
    return jsonResponse({ error: "Unable to generate ennoia itinerary." }, 502);
  }
});

async function readJsonBody(
  request: Request,
): Promise<{ ok: true; body: JsonMap } | { ok: false; error: string }> {
  try {
    const body = await request.json();
    if (!isJsonMap(body)) {
      return { ok: false, error: "Request body must be a JSON object." };
    }
    return { ok: true, body };
  } catch (_) {
    return { ok: false, error: "Request body must be valid JSON." };
  }
}

function validateFields(body: JsonMap, fields: string[]): string | null {
  for (const field of fields) {
    const value = body[field];
    if (typeof value !== "string" || value.trim().length === 0) {
      return `Missing or invalid field: ${field}.`;
    }
  }
  return null;
}

function readEnnoiaSecrets():
  | { ok: true; value: EnnoiaSecrets }
  | { ok: false; missing: string[] } {
  const endpoint = Deno.env.get("ENNOIA_API_ENDPOINT");
  const project = Deno.env.get("ENNOIA_PROJECT");
  const apiKey = Deno.env.get("ENNOIA_API_KEY");
  const hash = Deno.env.get("ENNOIA_ITINERARY_HASH");
  const userId = Deno.env.get("ENNOIA_USER_ID") ?? "norigo-demo-user";

  const requiredSecrets: Array<[string, string | undefined]> = [
    ["ENNOIA_API_ENDPOINT", endpoint],
    ["ENNOIA_PROJECT", project],
    ["ENNOIA_API_KEY", apiKey],
    ["ENNOIA_ITINERARY_HASH", hash],
  ];
  const missing = requiredSecrets
    .filter(([, value]) => !value)
    .map(([name]) => name);

  if (missing.length > 0) return { ok: false, missing };

  return {
    ok: true,
    value: {
      endpoint: endpoint!,
      project: project!,
      apiKey: apiKey!,
      hash: hash!,
      userId,
    },
  };
}

function parseJsonText(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch (_) {
    const jsonLike = extractJsonLikeText(text);
    if (!jsonLike) throw new Error("Response was not valid JSON.");
    return JSON.parse(jsonLike);
  }
}

function extractAgentPayload(decoded: unknown): JsonMap {
  const openAiContent = extractOpenAiContent(decoded);
  const payload = openAiContent ? parseJsonText(openAiContent) : decoded;

  if (Array.isArray(payload)) return { items: payload };
  if (isJsonMap(payload)) return payload;

  throw new Error("ennoia response payload was not a JSON object.");
}

function extractOpenAiContent(decoded: unknown): string | null {
  if (!isJsonMap(decoded)) return null;
  const choices = decoded.choices;
  if (!Array.isArray(choices) || choices.length === 0) return null;

  const firstChoice = choices[0];
  if (!isJsonMap(firstChoice)) return null;

  const message = firstChoice.message;
  if (isJsonMap(message) && typeof message.content === "string") {
    return message.content;
  }

  return typeof firstChoice.text === "string" ? firstChoice.text : null;
}

function extractJsonLikeText(content: string): string | null {
  const trimmed = content.trim();
  const objectStart = trimmed.indexOf("{");
  const objectEnd = trimmed.lastIndexOf("}");
  const arrayStart = trimmed.indexOf("[");
  const arrayEnd = trimmed.lastIndexOf("]");

  const hasObject = objectStart !== -1 && objectEnd > objectStart;
  const hasArray = arrayStart !== -1 && arrayEnd > arrayStart;

  if (hasObject && (!hasArray || objectStart < arrayStart)) {
    return trimmed.slice(objectStart, objectEnd + 1);
  }
  if (hasArray) return trimmed.slice(arrayStart, arrayEnd + 1);
  return null;
}

function withSourceMetadata(payload: JsonMap): JsonMap {
  return {
    ...payload,
    source: "ennoia",
    source_type: persistedSourceType,
    sourceNote:
      stringValue(payload, ["sourceNote", "source_note", "evidence"]) ??
        sourceNote,
  };
}

function validateItineraryPayload(payload: JsonMap): string | null {
  const data = nestedItineraryMap(payload);
  const items = listValue(data, [
    "items",
    "itinerary",
    "itineraryItems",
    "itinerary_items",
    "places",
  ]);

  if (items.length < 5) {
    return "ennoia itinerary must include at least 5 KTO-backed items.";
  }

  const missingContentId = items.slice(0, 5).some((item) => {
    if (!isJsonMap(item)) return true;
    return !stringValue(item, [
      "kto_content_id",
      "ktoContentId",
      "contentId",
      "content_id",
      "contentid",
    ]);
  });

  if (missingContentId) {
    return "ennoia itinerary items must include kto_content_id values.";
  }

  return null;
}

async function persistItineraryPlan(
  requestPayload: ItineraryRequest,
  result: JsonMap,
): Promise<PersistenceResult> {
  const table = "itinerary_plans" as const;
  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

  if (!supabaseUrl || !serviceRoleKey) {
    return {
      saved: false,
      table,
      error: "SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY is not configured.",
    };
  }

  const data = nestedItineraryMap(result);
  const row = {
    date_label:
      stringValue(data, [
        "dateLabel",
        "date_label",
        "travelDate",
        "travel_date",
      ]) ?? requestPayload.travel_date,
    summary: stringValue(data, ["title", "summary"]) ?? "AI Itinerary Planner",
    time_saved:
      stringValue(data, [
        "estimatedTimeSaved",
        "estimated_time_saved",
        "timeSaved",
      ]) ?? null,
    source_note:
      stringValue(result, ["sourceNote", "source_note"]) ?? sourceNote,
    raw_json: {
      request: requestPayload,
      result,
    },
    source_type: persistedSourceType,
  };

  const response = await fetch(
    `${supabaseUrl.replace(/\/+$/, "")}/rest/v1/${table}`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${serviceRoleKey}`,
        apikey: serviceRoleKey,
        "Content-Type": "application/json; charset=utf-8",
        Prefer: "return=representation",
      },
      body: JSON.stringify(row),
    },
  );

  const responseText = await response.text();
  if (!response.ok) {
    console.error("itinerary_plans insert failed", response.status, responseText);
    return {
      saved: false,
      table,
      error: `Supabase insert failed with status ${response.status}.`,
    };
  }

  const inserted = safeJsonOrText(responseText);
  const id = Array.isArray(inserted) && isJsonMap(inserted[0]) &&
      typeof inserted[0].id === "string"
    ? inserted[0].id
    : undefined;

  return { saved: true, table, id };
}

function nestedItineraryMap(payload: JsonMap): JsonMap {
  for (const key of ["itinerary", "plan", "result", "data"]) {
    const value = payload[key];
    if (isJsonMap(value)) return value;
  }
  return payload;
}

function listValue(payload: JsonMap, keys: string[]): unknown[] {
  for (const key of keys) {
    const value = payload[key];
    if (Array.isArray(value)) return value;
  }
  return [];
}

function stringValue(payload: JsonMap, keys: string[]): string | null {
  for (const key of keys) {
    const value = payload[key];
    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }
    if (typeof value === "number") return value.toString();
  }
  return null;
}

function safeJsonOrText(text: string): unknown {
  if (text.trim().length === 0) return null;
  try {
    return JSON.parse(text);
  } catch (_) {
    return text;
  }
}

function isJsonMap(value: unknown): value is JsonMap {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function jsonResponse(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json; charset=utf-8",
    },
  });
}
