type ItineraryRequest = {
  user_language: string;
  trip_days: string;
  base_location: string;
  travel_date: string;
  interests: string;
  companion_type: string;
  crowd_preference: string;
};

type JsonMap = Record<string, unknown>;

type EnnoiaSecrets = {
  endpoint: string;
  project: string;
  apiKey: string;
  hash: string;
  ktoServiceKey: string;
};

type KtoPlace = {
  title: string;
  contentid: string;
  contenttypeid: string;
  addr1: string;
  firstimage: string;
  mapx?: string;
  mapy?: string;
};

type KtoDataResult = {
  items: KtoPlace[];
  sourceType: "kto_openapi_ennoia" | "kto_openapi_fallback";
  fallbackReason?: string;
};

type PersistenceResult = {
  saved: boolean;
  table: "itinerary_plans";
  id?: string;
  error?: string;
};

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const requiredFields: Array<keyof ItineraryRequest> = [
  "user_language",
  "trip_days",
  "base_location",
  "travel_date",
  "interests",
  "companion_type",
  "crowd_preference",
];

const ktoSourceNote =
  "Generated by ennoia using Korea Tourism Organization OpenAPI data supplied by the Edge Function.";
const ktoFallbackSourceNote =
  "Generated by ennoia using demo KTO_DATA because Korea Tourism Organization OpenAPI data was unavailable.";

const fallbackKtoData: KtoPlace[] = [
  {
    title: "경복궁",
    contentid: "126508",
    contenttypeid: "12",
    addr1: "서울특별시 종로구 사직로 161",
    firstimage: "",
  },
  {
    title: "북촌한옥마을",
    contentid: "126537",
    contenttypeid: "12",
    addr1: "서울특별시 종로구 계동길 37",
    firstimage: "",
  },
  {
    title: "광장시장",
    contentid: "132183",
    contenttypeid: "38",
    addr1: "서울특별시 종로구 창경궁로 88",
    firstimage: "",
  },
  {
    title: "익선동 한옥거리",
    contentid: "2650046",
    contenttypeid: "12",
    addr1: "서울특별시 종로구 익선동",
    firstimage: "",
  },
  {
    title: "남산서울타워",
    contentid: "126535",
    contenttypeid: "12",
    addr1: "서울특별시 용산구 남산공원길 105",
    firstimage: "",
  },
];

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed." }, 405);
  }

  const bodyResult = await readJsonBody(request);
  if (!bodyResult.ok) {
    return jsonResponse({ error: bodyResult.error }, 400);
  }

  const validationError = validateFields(bodyResult.body, requiredFields);
  if (validationError) {
    return jsonResponse({ error: validationError }, 400);
  }

  const secrets = readEnnoiaSecrets();
  if (!secrets.ok) {
    return jsonResponse(
      { error: `Missing Edge Function secrets: ${secrets.missing.join(", ")}.` },
      500,
    );
  }

  const params = bodyResult.body as ItineraryRequest;

  try {
    const ktoData = await buildKtoData(params, secrets.value.ktoServiceKey);
    const ennoiaPayload = buildEnnoiaPayload(
      secrets.value.hash,
      params,
      ktoData,
    );

    const ennoiaResponse = await fetch(secrets.value.endpoint, {
      method: "POST",
      headers: {
        project: secrets.value.project,
        apiKey: secrets.value.apiKey,
        "Content-Type": "application/json; charset=utf-8",
      },
      body: JSON.stringify(ennoiaPayload),
    });

    const responseText = await ennoiaResponse.text();
    if (!ennoiaResponse.ok) {
      return jsonResponse(
        {
          error: "ennoia Itinerary API Agent request failed.",
          status: ennoiaResponse.status,
          detail: safeJsonOrText(responseText),
        },
        ennoiaResponse.status,
      );
    }

    const decoded = parseJsonText(responseText);
    const payload = normalizeItineraryPayload(
      withSourceMetadata(extractAgentPayload(decoded), ktoData),
      ktoData.items,
    );
    const payloadError = validateItineraryPayload(payload);
    if (payloadError) {
      return jsonResponse({ error: payloadError }, 502);
    }

    const persistence = await persistItineraryPlan(params, payload);

    return jsonResponse(
      {
        ...payload,
        persistence,
        persisted: persistence.saved,
        persistedPlanId: persistence.id,
      },
      200,
    );
  } catch (error) {
    console.error(
      "ennoia itinerary request failed",
      error instanceof Error ? error.message : "unknown error",
    );
    return jsonResponse({ error: "Unable to generate ennoia itinerary." }, 502);
  }
});

async function readJsonBody(
  request: Request,
): Promise<{ ok: true; body: JsonMap } | { ok: false; error: string }> {
  try {
    const body = await request.json();
    if (!isJsonMap(body)) {
      return { ok: false, error: "Request body must be a JSON object." };
    }
    return { ok: true, body };
  } catch (_) {
    return { ok: false, error: "Request body must be valid JSON." };
  }
}

function validateFields(body: JsonMap, fields: string[]): string | null {
  for (const field of fields) {
    const value = body[field];
    if (typeof value !== "string" || value.trim().length === 0) {
      return `Missing or invalid field: ${field}.`;
    }
  }
  return null;
}

function readEnnoiaSecrets():
  | { ok: true; value: EnnoiaSecrets }
  | { ok: false; missing: string[] } {
  const endpoint = Deno.env.get("ENNOIA_API_ENDPOINT");
  const project = Deno.env.get("ENNOIA_PROJECT");
  const apiKey = Deno.env.get("ENNOIA_API_KEY");
  const hash = Deno.env.get("ENNOIA_ITINERARY_API_HASH");
  const ktoServiceKey = Deno.env.get("KTO_SERVICE_KEY");

  const requiredSecrets: Array<[string, string | undefined]> = [
    ["ENNOIA_API_ENDPOINT", endpoint],
    ["ENNOIA_PROJECT", project],
    ["ENNOIA_API_KEY", apiKey],
    ["ENNOIA_ITINERARY_API_HASH", hash],
    ["KTO_SERVICE_KEY", ktoServiceKey],
  ];
  const missing = requiredSecrets
    .filter(([, value]) => !value)
    .map(([name]) => name);

  if (missing.length > 0) return { ok: false, missing };

  return {
    ok: true,
    value: {
      endpoint: endpoint!,
      project: project!,
      apiKey: apiKey!,
      hash: hash!,
      ktoServiceKey: ktoServiceKey!,
    },
  };
}

async function buildKtoData(
  requestPayload: ItineraryRequest,
  serviceKey: string,
): Promise<KtoDataResult> {
  const keywords = keywordsFromInterests(requestPayload.interests);
  const placesByContentId = new Map<string, KtoPlace>();

  try {
    for (const keyword of keywords) {
      const places = await fetchKtoKeywordResults(keyword, serviceKey);
      for (const place of places) {
        if (!place.contentid || placesByContentId.has(place.contentid)) {
          continue;
        }
        placesByContentId.set(place.contentid, place);
        if (placesByContentId.size >= 5) break;
      }
      if (placesByContentId.size >= 5) break;
    }
  } catch (error) {
    console.error(
      "KTO OpenAPI request failed",
      error instanceof Error ? error.message : "unknown error",
    );
    return {
      items: fallbackKtoData,
      sourceType: "kto_openapi_fallback",
      fallbackReason: "KTO OpenAPI request failed.",
    };
  }

  const items = Array.from(placesByContentId.values()).slice(0, 5);
  if (items.length < 5) {
    return {
      items: fallbackKtoData,
      sourceType: "kto_openapi_fallback",
      fallbackReason: "KTO OpenAPI returned fewer than five unique places.",
    };
  }

  return { items, sourceType: "kto_openapi_ennoia" };
}

function keywordsFromInterests(interests: string): string[] {
  const normalized = interests.toLowerCase();
  const keywords: string[] = [];

  const add = (...values: string[]) => {
    for (const value of values) {
      if (!keywords.includes(value)) keywords.push(value);
    }
  };

  if (normalized.includes("palace")) add("경복궁");
  if (normalized.includes("hanok")) add("북촌한옥마을");
  if (normalized.includes("traditional market") || normalized.includes("market")) {
    add("광장시장");
  }
  if (normalized.includes("dessert") || normalized.includes("cafe")) {
    add("익선동", "명동 카페");
  }
  if (normalized.includes("photo")) add("익선동", "경복궁", "남산서울타워");
  if (normalized.includes("night view") || normalized.includes("night")) {
    add("남산서울타워");
  }

  if (keywords.length == 0) {
    add("경복궁", "북촌한옥마을", "광장시장", "익선동", "남산서울타워");
  }

  return keywords;
}

async function fetchKtoKeywordResults(
  keyword: string,
  serviceKey: string,
): Promise<KtoPlace[]> {
  const response = await fetch(ktoSearchKeywordUrl(keyword, serviceKey));
  const responseText = await response.text();

  if (!response.ok) {
    throw new Error(`KTO OpenAPI failed with status ${response.status}.`);
  }

  const decoded = safeJsonOrText(responseText);
  if (!isJsonMap(decoded)) {
    throw new Error("KTO OpenAPI response was not JSON.");
  }

  return ktoItemsFromResponse(decoded).map(normalizeKtoPlace).filter(Boolean) as
    KtoPlace[];
}

function ktoSearchKeywordUrl(keyword: string, serviceKey: string): string {
  const params = new URLSearchParams({
    MobileOS: "ETC",
    MobileApp: "NoriGo",
    _type: "json",
    numOfRows: "10",
    pageNo: "1",
    keyword,
  });
  const normalizedServiceKey = serviceKey.includes("%")
    ? serviceKey
    : encodeURIComponent(serviceKey);

  return `https://apis.data.go.kr/B551011/KorService2/searchKeyword2?serviceKey=${normalizedServiceKey}&${params}`;
}

function ktoItemsFromResponse(response: JsonMap): JsonMap[] {
  const body = isJsonMap(response.response) && isJsonMap(response.response.body)
    ? response.response.body
    : null;
  const items = body && isJsonMap(body.items) ? body.items.item : null;

  if (Array.isArray(items)) return items.filter(isJsonMap);
  if (isJsonMap(items)) return [items];
  return [];
}

function normalizeKtoPlace(item: JsonMap): KtoPlace | null {
  const title = stringValue(item, ["title"]);
  const contentid = stringValue(item, ["contentid", "contentId", "content_id"]);
  if (!title || !contentid) return null;

  return {
    title,
    contentid,
    contenttypeid:
      stringValue(item, ["contenttypeid", "contentTypeId", "content_type_id"]) ??
        "",
    addr1: stringValue(item, ["addr1"]) ?? "",
    firstimage: stringValue(item, ["firstimage", "firstImage"]) ?? "",
    mapx: stringValue(item, ["mapx", "mapX"]),
    mapy: stringValue(item, ["mapy", "mapY"]),
  };
}

function buildEnnoiaPayload(
  hash: string,
  requestPayload: ItineraryRequest,
  ktoData: KtoDataResult,
): JsonMap {
  const ktoDataJson = JSON.stringify(ktoData.items);

  return {
    hash,
    params: {
      ...requestPayload,
      kto_data: ktoDataJson,
      source_type: ktoData.sourceType,
    },
    messages: [
      {
        role: "user",
        content:
          "Create exactly 5 itinerary items using only the KTO_DATA JSON below. " +
          "Do not call MCP, tools, connectors, or external APIs. " +
          "Return valid JSON only with id, dateLabel, title, estimatedTimeSaved, " +
          "sourceNote, and items. Each item must include id, order, time, " +
          "placeName, crowdLevel, stayTime, aiTip, kto_content_id, " +
          "contenttypeid, addr1, firstimage, mapX, and mapY when available. " +
          "At least 3 items must keep their KTO content IDs.\n\n" +
          `Traveler request: ${JSON.stringify(requestPayload)}\n\n` +
          `KTO_DATA: ${ktoDataJson}`,
      },
    ],
  };
}

function parseJsonText(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch (_) {
    const jsonLike = extractJsonLikeText(text);
    if (!jsonLike) throw new Error("Response was not valid JSON.");
    return JSON.parse(jsonLike);
  }
}

function extractAgentPayload(decoded: unknown): JsonMap {
  const openAiContent = extractOpenAiContent(decoded);
  const payload = openAiContent ? parseJsonText(openAiContent) : decoded;

  if (Array.isArray(payload)) return { items: payload };
  if (isJsonMap(payload)) return payload;

  throw new Error("ennoia response payload was not a JSON object.");
}

function extractOpenAiContent(decoded: unknown): string | null {
  if (!isJsonMap(decoded)) return null;
  const choices = decoded.choices;
  if (!Array.isArray(choices) || choices.length === 0) return null;

  const firstChoice = choices[0];
  if (!isJsonMap(firstChoice)) return null;

  const message = firstChoice.message;
  if (isJsonMap(message) && typeof message.content === "string") {
    return message.content;
  }

  return typeof firstChoice.text === "string" ? firstChoice.text : null;
}

function extractJsonLikeText(content: string): string | null {
  const trimmed = content.trim();
  const objectStart = trimmed.indexOf("{");
  const objectEnd = trimmed.lastIndexOf("}");
  const arrayStart = trimmed.indexOf("[");
  const arrayEnd = trimmed.lastIndexOf("]");

  const hasObject = objectStart !== -1 && objectEnd > objectStart;
  const hasArray = arrayStart !== -1 && arrayEnd > arrayStart;

  if (hasObject && (!hasArray || objectStart < arrayStart)) {
    return trimmed.slice(objectStart, objectEnd + 1);
  }
  if (hasArray) return trimmed.slice(arrayStart, arrayEnd + 1);
  return null;
}

function withSourceMetadata(payload: JsonMap, ktoData: KtoDataResult): JsonMap {
  const note = ktoData.sourceType == "kto_openapi_ennoia"
    ? ktoSourceNote
    : ktoFallbackSourceNote;

  return {
    ...payload,
    source: ktoData.sourceType,
    source_type: ktoData.sourceType,
    sourceType: ktoData.sourceType,
    sourceNote:
      stringValue(payload, ["sourceNote", "source_note", "evidence"]) ?? note,
    kto_data_source: ktoData.sourceType,
    kto_data: ktoData.items,
    fallbackReason: ktoData.fallbackReason,
  };
}

function normalizeItineraryPayload(payload: JsonMap, ktoData: KtoPlace[]): JsonMap {
  const data = nestedItineraryMap(payload);
  const items = listValue(data, [
    "items",
    "itinerary",
    "itineraryItems",
    "itinerary_items",
    "places",
  ]);
  if (!Array.isArray(items)) return payload;

  const normalizedItems = items.map((item, index) => {
    if (!isJsonMap(item)) return item;

    const contentId = stringValue(item, [
      "kto_content_id",
      "ktoContentId",
      "contentId",
      "content_id",
      "contentid",
    ]);
    const match = contentId
      ? ktoData.find((place) => place.contentid == contentId)
      : matchKtoPlaceByTitle(item, ktoData);

    if (!match) return item;

    return {
      ...item,
      id: stringValue(item, ["id"]) ?? slug(match.title),
      order: numberValue(item, ["order", "sequence"]) ?? index + 1,
      placeName: stringValue(item, ["placeName", "place_name", "name", "title"]) ??
        match.title,
      kto_content_id: contentId ?? match.contentid,
      contentId: contentId ?? match.contentid,
      contenttypeid:
        stringValue(item, ["contenttypeid", "contentTypeId"]) ??
          match.contenttypeid,
      addr1: stringValue(item, ["addr1"]) ?? match.addr1,
      firstimage: stringValue(item, ["firstimage", "firstImage"]) ??
        match.firstimage,
      mapX: stringValue(item, ["mapX", "mapx"]) ?? match.mapx,
      mapY: stringValue(item, ["mapY", "mapy"]) ?? match.mapy,
    };
  });

  if (data === payload) {
    return { ...payload, items: normalizedItems };
  }

  for (const key of ["itinerary", "plan", "result", "data"]) {
    if (payload[key] === data) {
      return { ...payload, [key]: { ...data, items: normalizedItems } };
    }
  }

  return payload;
}

function matchKtoPlaceByTitle(item: JsonMap, ktoData: KtoPlace[]): KtoPlace | null {
  const placeName = stringValue(item, [
    "placeName",
    "place_name",
    "name",
    "title",
  ]);
  if (!placeName) return null;

  return ktoData.find((place) =>
    placeName.includes(place.title) || place.title.includes(placeName)
  ) ?? null;
}

function validateItineraryPayload(payload: JsonMap): string | null {
  const data = nestedItineraryMap(payload);
  const items = listValue(data, [
    "items",
    "itinerary",
    "itineraryItems",
    "itinerary_items",
    "places",
  ]);

  if (items.length != 5) {
    return "ennoia itinerary must include exactly 5 items.";
  }

  const ktoContentIdCount = items.filter((item) => {
    if (!isJsonMap(item)) return false;
    return Boolean(stringValue(item, [
      "kto_content_id",
      "ktoContentId",
      "contentId",
      "content_id",
      "contentid",
    ]));
  }).length;

  if (ktoContentIdCount < 3) {
    return "ennoia itinerary must include at least 3 kto_content_id values.";
  }

  return null;
}

async function persistItineraryPlan(
  requestPayload: ItineraryRequest,
  result: JsonMap,
): Promise<PersistenceResult> {
  const table = "itinerary_plans" as const;
  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

  if (!supabaseUrl || !serviceRoleKey) {
    return {
      saved: false,
      table,
      error: "SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY is not configured.",
    };
  }

  const data = nestedItineraryMap(result);
  const row = {
    date_label:
      stringValue(data, [
        "dateLabel",
        "date_label",
        "travelDate",
        "travel_date",
      ]) ?? requestPayload.travel_date,
    summary: stringValue(data, ["title", "summary"]) ?? "AI Itinerary Planner",
    time_saved:
      stringValue(data, [
        "estimatedTimeSaved",
        "estimated_time_saved",
        "timeSaved",
      ]) ?? null,
    source_note:
      stringValue(result, ["sourceNote", "source_note"]) ?? ktoSourceNote,
    raw_json: {
      request: requestPayload,
      result,
    },
    source_type:
      stringValue(result, ["source_type", "sourceType", "source"]) ??
        "kto_openapi_ennoia",
  };

  const response = await fetch(
    `${supabaseUrl.replace(/\/+$/, "")}/rest/v1/${table}`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${serviceRoleKey}`,
        apikey: serviceRoleKey,
        "Content-Type": "application/json; charset=utf-8",
        Prefer: "return=representation",
      },
      body: JSON.stringify(row),
    },
  );

  const responseText = await response.text();
  if (!response.ok) {
    console.error("itinerary_plans insert failed", response.status, responseText);
    return {
      saved: false,
      table,
      error: `Supabase insert failed with status ${response.status}.`,
    };
  }

  const inserted = safeJsonOrText(responseText);
  const id = Array.isArray(inserted) && isJsonMap(inserted[0]) &&
      typeof inserted[0].id === "string"
    ? inserted[0].id
    : undefined;

  return { saved: true, table, id };
}

function nestedItineraryMap(payload: JsonMap): JsonMap {
  for (const key of ["itinerary", "plan", "result", "data"]) {
    const value = payload[key];
    if (isJsonMap(value)) return value;
  }
  return payload;
}

function listValue(payload: JsonMap, keys: string[]): unknown[] {
  for (const key of keys) {
    const value = payload[key];
    if (Array.isArray(value)) return value;
  }
  return [];
}

function stringValue(payload: JsonMap, keys: string[]): string | null {
  for (const key of keys) {
    const value = payload[key];
    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }
    if (typeof value === "number") return value.toString();
  }
  return null;
}

function numberValue(payload: JsonMap, keys: string[]): number | null {
  for (const key of keys) {
    const value = payload[key];
    if (typeof value === "number") return value;
    if (typeof value === "string") {
      const parsed = Number(value);
      if (!Number.isNaN(parsed)) return parsed;
    }
  }
  return null;
}

function slug(value: string): string {
  const slugged = value
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slugged || "recommended-stop";
}

function safeJsonOrText(text: string): unknown {
  if (text.trim().length === 0) return null;
  try {
    return JSON.parse(text);
  } catch (_) {
    return text;
  }
}

function isJsonMap(value: unknown): value is JsonMap {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function jsonResponse(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json; charset=utf-8",
    },
  });
}
