import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:norigo/app/router.dart';
import 'package:norigo/features/itinerary/data/mock_itinerary_repository.dart';
import 'package:norigo/features/itinerary/presentation/ai_itinerary_planner_screen.dart';

void main() {
  testWidgets('AiItineraryPlannerScreen renders core itinerary content', (
    tester,
  ) async {
    await _pumpPlanner(tester);

    expect(find.text('AI Itinerary Planner'), findsOneWidget);
    expect(find.text('Crowd-aware itinerary'), findsOneWidget);
    expect(find.text('May 18, Sun'), findsOneWidget);
    expect(find.byKey(const ValueKey('selected-time-09:00')), findsOneWidget);
    expect(find.byKey(const ValueKey('whyThisRouteButton')), findsOneWidget);
    expect(find.byKey(const ValueKey('savePlanButton')), findsOneWidget);

    for (final placeName in [
      'Gyeongbokgung Palace',
      'Bukchon Hanok Village',
      'Dessert Cafe',
      'Seongsu Select Shop',
      'N Seoul Tower',
    ]) {
      expect(find.text(placeName), findsOneWidget);
    }
  });

  testWidgets('why this route button shows explanation', (tester) async {
    await _pumpPlanner(tester);

    await tester.tap(find.byKey(const ValueKey('whyThisRouteButton')));
    await tester.pumpAndSettle();

    expect(
      find.textContaining('This plan avoids peak crowd times'),
      findsOneWidget,
    );
    expect(
      find.textContaining('generated by ennoia using KTO OpenAPI data'),
      findsOneWidget,
    );
  });

  testWidgets('save this plan button shows local save snackbar', (
    tester,
  ) async {
    await _pumpPlanner(tester);

    await tester.tap(find.byKey(const ValueKey('savePlanButton')));
    await tester.pump();

    expect(find.text('Itinerary saved locally for now.'), findsOneWidget);
  });

  testWidgets('dessert cafe card opens crowd alert demo route', (tester) async {
    await _pumpPlanner(
      tester,
      routes: {
        AppRoutes.itineraryCrowdAlert: (_) =>
            const Scaffold(body: Placeholder(key: ValueKey('crowdAlertRoute'))),
      },
    );

    final trigger = find.byKey(const ValueKey('crowd-alert-demo-dessert-cafe'));
    await tester.ensureVisible(trigger);
    await tester.tap(trigger);
    await tester.pumpAndSettle();

    expect(find.byKey(const ValueKey('crowdAlertRoute')), findsOneWidget);
  });

  testWidgets('missing header image asset falls back without crashing', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      headerAsset: 'assets/images/itinerary/missing_header.png',
    );
    await tester.pumpAndSettle();

    expect(tester.takeException(), isNull);
    expect(find.text('AI Itinerary Planner'), findsOneWidget);
  });

  test('mock repository returns five itinerary items', () async {
    final plan = await const MockItineraryRepository().fetchPlan();

    expect(plan.items, hasLength(5));
    expect(plan.sourceType, 'mock');
    expect(plan.items.first.placeName, 'Gyeongbokgung Palace');
  });
}

Future<void> _pumpPlanner(
  WidgetTester tester, {
  String? headerAsset,
  Map<String, WidgetBuilder>? routes,
}) async {
  await tester.binding.setSurfaceSize(const Size(430, 932));
  addTearDown(() => tester.binding.setSurfaceSize(null));

  await tester.pumpWidget(
    MaterialApp(
      home: AiItineraryPlannerScreen(
        headerAsset:
            headerAsset ?? 'assets/images/itinerary/itinerary_header_bg.png',
      ),
      routes: routes ?? const {},
    ),
  );
  await tester.pumpAndSettle();
}
