import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:norigo/features/crowd/data/seoul_realtime_risk_repository.dart';
import 'package:norigo/features/crowd/domain/seoul_realtime_risk.dart';
import 'package:norigo/features/itinerary/application/itinerary_session_store.dart';
import 'package:norigo/features/itinerary/data/mock_itinerary_repository.dart';
import 'package:norigo/features/itinerary/data/itinerary_repository.dart';
import 'package:norigo/features/itinerary/domain/itinerary_item.dart';
import 'package:norigo/features/itinerary/domain/itinerary_plan.dart';
import 'package:norigo/features/itinerary/presentation/ai_itinerary_planner_screen.dart';

void main() {
  setUp(ItinerarySessionStore.resetForTesting);

  testWidgets('AiItineraryPlannerScreen renders core itinerary content', (
    tester,
  ) async {
    await _pumpPlanner(tester);

    expect(find.text('AI Itinerary Planner'), findsOneWidget);
    expect(find.text('Crowd-aware itinerary'), findsOneWidget);
    expect(find.text('May 18, Sun'), findsOneWidget);
    expect(find.byKey(const ValueKey('selected-time-09:00')), findsOneWidget);
    expect(find.byKey(const ValueKey('whyThisRouteButton')), findsOneWidget);
    expect(find.byKey(const ValueKey('savePlanButton')), findsOneWidget);

    for (final placeName in [
      'Gyeongbokgung Palace',
      'Bukchon Hanok Village',
      'Dessert Cafe',
      'Seongsu Select Shop',
      'N Seoul Tower',
    ]) {
      expect(find.text(placeName), findsOneWidget);
    }
  });

  testWidgets('why this route button shows explanation', (tester) async {
    await _pumpPlanner(tester);

    await tester.tap(find.byKey(const ValueKey('whyThisRouteButton')));
    await tester.pumpAndSettle();

    expect(
      find.textContaining('This plan avoids peak crowd times'),
      findsOneWidget,
    );
    expect(
      find.textContaining('generated by ennoia using KTO OpenAPI data'),
      findsOneWidget,
    );
  });

  testWidgets('save this plan button opens crowd alert for selected item', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      riskRepository: const _StaticSeoulRiskRepository(_veryHighRisk),
    );

    await tester.tap(find.byKey(const ValueKey('savePlanButton')));
    await tester.pumpAndSettle();

    expect(find.text('Crowd Alert'), findsOneWidget);
    expect(find.text('Gyeongbokgung Palace'), findsWidgets);
  });

  testWidgets('itinerary card opens crowd alert with actual item', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      riskRepository: const _StaticSeoulRiskRepository(_veryHighRisk),
    );

    final trigger = find.byKey(const ValueKey('crowd-alert-item-dessert-cafe'));
    await tester.ensureVisible(trigger);
    await tester.tap(trigger);
    await tester.pumpAndSettle();

    expect(find.text('Crowd Alert'), findsOneWidget);
    expect(find.text('Dessert Cafe'), findsWidgets);
    expect(find.text('Cafe Arte'), findsNothing);
    expect(find.text('Seoul Real-time'), findsOneWidget);
    expect(find.text('85'), findsOneWidget);
  });

  testWidgets('itinerary card shows Crowd rising without opening alert', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      riskRepository: const _StaticSeoulRiskRepository(_highWatchRisk),
    );

    final trigger = find.byKey(const ValueKey('crowd-alert-item-dessert-cafe'));
    await tester.ensureVisible(trigger);
    await tester.tap(trigger);
    await tester.pumpAndSettle();

    expect(find.text('Crowd Alert'), findsNothing);
    expect(find.text('Crowd rising'), findsWidgets);
  });

  testWidgets('Seoul risk API failure does not crash or open alert', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      riskRepository: const _ThrowingSeoulRiskRepository(),
    );

    final trigger = find.byKey(const ValueKey('crowd-alert-item-dessert-cafe'));
    await tester.ensureVisible(trigger);
    await tester.tap(trigger);
    await tester.pumpAndSettle();

    expect(find.text('Crowd Alert'), findsNothing);
    expect(tester.takeException(), isNull);
  });

  testWidgets('missing header image asset falls back without crashing', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      headerAsset: 'assets/images/itinerary/missing_header.png',
    );
    await tester.pumpAndSettle();

    expect(tester.takeException(), isNull);
    expect(find.text('AI Itinerary Planner'), findsOneWidget);
  });

  testWidgets('generate with ennoia falls back when env is missing', (
    tester,
  ) async {
    await _pumpPlanner(tester);

    await tester.tap(find.byKey(const ValueKey('generateWithEnnoiaButton')));
    await tester.pumpAndSettle();

    expect(find.text('Mock ennoia'), findsOneWidget);
    expect(find.text('Gyeongbokgung Palace'), findsOneWidget);
    expect(tester.takeException(), isNull);
  });

  testWidgets('renders KTO source badge and enriched item metadata', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      repository: const _StaticItineraryRepository(
        ItineraryPlan(
          id: 'kto-route',
          dateLabel: 'May 18, Sun',
          title: 'Palace + market route',
          estimatedTimeSaved: '1h 10m',
          sourceType: 'kto_openapi_ennoia',
          sourceBadge: 'KTO OpenAPI + ennoia',
          sourceNote: 'Real KTO candidates were used.',
          persistedPlanId: 'plan-123',
          items: [
            ItineraryItem(
              id: 'gyeongbokgung-palace',
              order: 1,
              time: '09:00',
              placeName: 'Gyeongbokgung Palace',
              crowdLevel: ItineraryCrowdLevel.low,
              stayTime: 'Stay 1h 30m',
              aiTip: 'Strong palace match.',
              contentId: '264337',
              cultureTip: 'Keep voices low near ceremonial areas.',
            ),
          ],
        ),
      ),
    );

    expect(find.text('KTO OpenAPI + ennoia'), findsOneWidget);
    expect(find.text('KTO 264337'), findsOneWidget);
    expect(find.text('Keep voices low near ceremonial areas.'), findsOneWidget);

    await tester.ensureVisible(find.byKey(const ValueKey('viewKtoDataButton')));
    await tester.tap(find.byKey(const ValueKey('viewKtoDataButton')));
    await tester.pumpAndSettle();

    expect(find.text('source_type'), findsOneWidget);
    expect(find.text('kto_openapi_ennoia'), findsOneWidget);
    expect(find.text('source_badge'), findsOneWidget);
    expect(find.text('KTO OpenAPI + ennoia'), findsWidgets);
    expect(find.text('ennoia generation'), findsOneWidget);
    expect(find.text('succeeded'), findsOneWidget);
    expect(find.text('persistedPlanId'), findsOneWidget);
    expect(find.text('plan-123'), findsOneWidget);
    expect(find.text('source_note'), findsOneWidget);
    expect(find.text('Real KTO candidates were used.'), findsOneWidget);
    expect(find.text('264337'), findsOneWidget);
  });

  testWidgets('itinerary screen shows selected Re-Trip replacement', (
    tester,
  ) async {
    ItinerarySessionStore.savePlan(
      const ItineraryPlan(
        id: 'saved-plan',
        dateLabel: 'May 18, Sun',
        title: 'Updated route',
        estimatedTimeSaved: '1h',
        items: [
          ItineraryItem(
            id: 'seoul-museum-of-art',
            order: 1,
            time: '09:00',
            placeName: 'Seoul Museum of Art',
            crowdLevel: ItineraryCrowdLevel.low,
            stayTime: 'Stay 1h',
            aiTip: 'Quiet indoor art stop near the palace route.',
            contentId: '130856',
          ),
        ],
      ),
    );

    await _pumpPlanner(tester);

    expect(find.text('Seoul Museum of Art'), findsOneWidget);
    expect(find.text('KTO 130856'), findsOneWidget);
  });

  testWidgets('refresh load keeps selected Re-Trip replacement', (
    tester,
  ) async {
    await _pumpPlanner(
      tester,
      repository: const _StaticItineraryRepository(
        ItineraryPlan(
          id: 'persisted-plan',
          persistedPlanId: '00000000-0000-4000-8000-000000000001',
          dateLabel: 'May 18, Sun',
          title: 'Updated route',
          estimatedTimeSaved: '1h',
          sourceType: 'kto_openapi_ennoia',
          sourceBadge: 'KTO OpenAPI + ennoia',
          items: [
            ItineraryItem(
              id: 'seoul-museum-of-art',
              order: 1,
              time: '09:00',
              placeName: 'Seoul Museum of Art',
              crowdLevel: ItineraryCrowdLevel.low,
              stayTime: 'Stay 1h',
              aiTip: 'Quiet indoor art stop near the palace route.',
              contentId: '130856',
            ),
          ],
        ),
      ),
    );

    expect(find.text('Seoul Museum of Art'), findsOneWidget);
    expect(find.text('KTO 130856'), findsOneWidget);
    expect(find.text('Deoksugung Daehanmun'), findsNothing);
  });

  test('mock repository returns five itinerary items', () async {
    final plan = await const MockItineraryRepository().fetchPlan();

    expect(plan.items, hasLength(5));
    expect(plan.sourceType, 'mock');
    expect(plan.items.first.placeName, 'Gyeongbokgung Palace');
  });
}

Future<void> _pumpPlanner(
  WidgetTester tester, {
  String? headerAsset,
  ItineraryRepository? repository,
  SeoulRealtimeRiskRepository? riskRepository,
  Map<String, WidgetBuilder>? routes,
}) async {
  await tester.binding.setSurfaceSize(const Size(430, 932));
  addTearDown(() => tester.binding.setSurfaceSize(null));

  await tester.pumpWidget(
    MaterialApp(
      home: AiItineraryPlannerScreen(
        headerAsset:
            headerAsset ?? 'assets/images/itinerary/itinerary_header_bg.png',
        repository: repository ?? const MockItineraryRepository(),
        seoulRealtimeRiskRepository:
            riskRepository ?? const _StaticSeoulRiskRepository(_lowRisk),
        autoGenerateOnOpen: false,
      ),
      routes: routes ?? const {},
    ),
  );
  await tester.pumpAndSettle();
}

class _StaticItineraryRepository implements ItineraryRepository {
  const _StaticItineraryRepository(this.plan);

  final ItineraryPlan plan;

  @override
  Future<ItineraryPlan> fetchPlan() async => plan;

  @override
  Future<ItineraryPlan> savePlan(ItineraryPlan plan) async => plan;
}

class _StaticSeoulRiskRepository implements SeoulRealtimeRiskRepository {
  const _StaticSeoulRiskRepository(this.risk);

  final SeoulRealtimeRisk risk;

  @override
  Future<SeoulRealtimeRisk> checkRisk(SeoulRealtimeRiskRequest request) async {
    return risk;
  }
}

class _ThrowingSeoulRiskRepository implements SeoulRealtimeRiskRepository {
  const _ThrowingSeoulRiskRepository();

  @override
  Future<SeoulRealtimeRisk> checkRisk(SeoulRealtimeRiskRequest request) async {
    return SeoulRealtimeRisk.unavailable(
      scheduledPlaceName: request.scheduledPlaceName,
    );
  }
}

const _lowRisk = SeoulRealtimeRisk(
  areaNm: '북촌한옥마을',
  matchedPlaceName: 'Bukchon Hanok Village',
  scheduledPlaceName: 'Bukchon Hanok Village',
  congestionLevel: '보통',
  congestionMessage: 'Normal crowd level.',
  populationMin: 100,
  populationMax: 200,
  populationTime: '2026-06-03 14:00',
  crowdScore: 45,
  incidentBonus: 0,
  riskScore: 45,
  riskLevel: 'Moderate',
  shouldAlert: false,
  triggerType: 'none',
  alertMessage: 'Bukchon is moderate.',
  riskReason: 'No incident data was used.',
  sourceType: 'seoul_realtime_citydata',
  sourceBadge: 'Seoul Real-time',
);

const _highWatchRisk = SeoulRealtimeRisk(
  areaNm: '북촌한옥마을',
  matchedPlaceName: 'Bukchon Hanok Village',
  scheduledPlaceName: 'Bukchon Hanok Village',
  congestionLevel: '약간 붐빔',
  congestionMessage: 'Crowd is rising.',
  populationMin: 1000,
  populationMax: 2000,
  populationTime: '2026-06-03 14:00',
  crowdScore: 70,
  incidentBonus: 0,
  riskScore: 70,
  riskLevel: 'High',
  shouldAlert: false,
  triggerType: 'crowd_watch',
  alertMessage: 'Bukchon crowd is rising.',
  riskReason: 'No incident data was used.',
  sourceType: 'seoul_realtime_citydata',
  sourceBadge: 'Seoul Real-time',
);

const _veryHighRisk = SeoulRealtimeRisk(
  areaNm: '북촌한옥마을',
  matchedPlaceName: 'Bukchon Hanok Village',
  scheduledPlaceName: 'Bukchon Hanok Village',
  congestionLevel: '붐빔',
  congestionMessage: 'Very crowded.',
  populationMin: 2000,
  populationMax: 3000,
  populationTime: '2026-06-03 14:00',
  crowdScore: 85,
  incidentBonus: 0,
  riskScore: 85,
  riskLevel: 'Very High',
  shouldAlert: true,
  triggerType: 'crowd_spike',
  alertMessage: 'Bukchon is very crowded.',
  riskReason: 'No incident data was used.',
  sourceType: 'seoul_realtime_citydata',
  sourceBadge: 'Seoul Real-time',
);
