import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:norigo/app/router.dart';
import 'package:norigo/features/itinerary/application/itinerary_controller.dart';
import 'package:norigo/features/itinerary/data/itinerary_repository.dart';
import 'package:norigo/features/itinerary/data/mock_itinerary_repository.dart';
import 'package:norigo/features/itinerary/domain/itinerary_item.dart';
import 'package:norigo/features/itinerary/domain/itinerary_plan.dart';

const _logoAsset = 'assets/images/splash/norigo_logo_full.png';
const _headerAsset = 'assets/images/itinerary/itinerary_header_bg.png';

class AiItineraryPlannerScreen extends StatefulWidget {
  const AiItineraryPlannerScreen({
    super.key,
    this.logoAsset = _logoAsset,
    this.headerAsset = _headerAsset,
    this.repository = const MockItineraryRepository(),
  });

  final String logoAsset;
  final String headerAsset;
  final ItineraryRepository repository;

  @override
  State<AiItineraryPlannerScreen> createState() =>
      _AiItineraryPlannerScreenState();
}

class _AiItineraryPlannerScreenState extends State<AiItineraryPlannerScreen> {
  late final ItineraryController _controller;
  int _selectedTimeIndex = 0;

  @override
  void initState() {
    super.initState();
    _controller = ItineraryController(repository: widget.repository);
    _controller.loadPlan();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _savePlan() async {
    final saved = await _controller.savePlan();
    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(
          saved
              ? 'Itinerary saved locally for now.'
              : _controller.errorMessage ?? 'Unable to save itinerary.',
        ),
      ),
    );
  }

  void _showRouteReason() {
    showModalBottomSheet<void>(
      context: context,
      showDragHandle: true,
      builder: (context) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Why this route?',
                  style: TextStyle(
                    color: _PlannerColors.deepPurple,
                    fontSize: 22,
                    fontWeight: FontWeight.w900,
                  ),
                ),
                const SizedBox(height: 12),
                const Text(
                  'This plan avoids peak crowd times, keeps travel distance '
                  'short, and balances culture, food, shopping, and sunset '
                  'views.',
                  style: TextStyle(
                    color: _PlannerColors.textSub,
                    fontSize: 16,
                    height: 1.42,
                    fontWeight: FontWeight.w500,
                  ),
                ),
                const SizedBox(height: 14),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(
                    color: _PlannerColors.lavender,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text(
                    'Later, this explanation will be generated by ennoia '
                    'using KTO OpenAPI data.',
                    style: TextStyle(
                      color: _PlannerColors.deepPurple,
                      fontSize: 14,
                      height: 1.35,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  void _handleBottomNavigation(int index) {
    if (index == 1) return;

    final route = switch (index) {
      0 => AppRoutes.home,
      2 => AppRoutes.cultureScan,
      _ => null,
    };

    if (route != null && AppRouter.routes.containsKey(route)) {
      Navigator.of(context).pushReplacementNamed(route);
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('This section will be connected later.')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle.dark.copyWith(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
        systemNavigationBarColor: _PlannerColors.white,
      ),
      child: Scaffold(
        backgroundColor: _PlannerColors.white,
        body: SafeArea(
          bottom: false,
          child: LayoutBuilder(
            builder: (context, constraints) {
              final pageWidth = math.min(constraints.maxWidth, 560.0);
              final scale = (pageWidth / 430.0).clamp(0.86, 1.06).toDouble();
              final safeBottom = MediaQuery.paddingOf(context).bottom;
              final navHeight = 76 * scale + safeBottom;
              final saveButtonBottom = navHeight + 12 * scale;

              return Center(
                child: SizedBox(
                  width: pageWidth,
                  child: AnimatedBuilder(
                    animation: _controller,
                    builder: (context, _) {
                      final plan = _controller.plan;

                      if (_controller.isLoading && plan == null) {
                        return const Center(
                          child: CircularProgressIndicator(
                            color: _PlannerColors.purple,
                          ),
                        );
                      }

                      if (plan == null) {
                        return _ErrorState(
                          message:
                              _controller.errorMessage ??
                              'Unable to load itinerary.',
                          onRetry: _controller.loadPlan,
                        );
                      }

                      return Stack(
                        children: [
                          SingleChildScrollView(
                            physics: const BouncingScrollPhysics(),
                            padding: EdgeInsets.fromLTRB(
                              20 * scale,
                              0,
                              20 * scale,
                              navHeight + 92 * scale,
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                _ItineraryHeader(
                                  plan: plan,
                                  logoAsset: widget.logoAsset,
                                  headerAsset: widget.headerAsset,
                                  scale: scale,
                                ),
                                _ControlsRow(
                                  dateLabel: plan.dateLabel,
                                  scale: scale,
                                  onWhyPressed: _showRouteReason,
                                ),
                                SizedBox(height: 14 * scale),
                                _TimeChipRow(
                                  times: plan.items
                                      .map((item) => item.time)
                                      .take(5)
                                      .toList(growable: false),
                                  selectedIndex: _selectedTimeIndex,
                                  scale: scale,
                                  onSelected: (index) {
                                    setState(() {
                                      _selectedTimeIndex = index;
                                    });
                                  },
                                ),
                                SizedBox(height: 16 * scale),
                                _ItineraryTimeline(
                                  items: plan.items,
                                  scale: scale,
                                ),
                                SizedBox(height: 12 * scale),
                                _RouteSummaryCard(plan: plan, scale: scale),
                              ],
                            ),
                          ),
                          Positioned(
                            left: 20 * scale,
                            right: 20 * scale,
                            bottom: saveButtonBottom,
                            child: _SavePlanButton(
                              isSaving: _controller.isSaving,
                              scale: scale,
                              onPressed: _savePlan,
                            ),
                          ),
                          Positioned(
                            left: 0,
                            right: 0,
                            bottom: 0,
                            child: _BottomNavigation(
                              selectedIndex: 1,
                              scale: scale,
                              height: navHeight,
                              safeBottom: safeBottom,
                              onChanged: _handleBottomNavigation,
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class _ItineraryHeader extends StatelessWidget {
  const _ItineraryHeader({
    required this.plan,
    required this.logoAsset,
    required this.headerAsset,
    required this.scale,
  });

  final ItineraryPlan plan;
  final String logoAsset;
  final String headerAsset;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 230 * scale,
      child: Stack(
        clipBehavior: Clip.none,
        children: [
          Positioned(
            right: -18 * scale,
            top: 28 * scale,
            width: 286 * scale,
            height: 146 * scale,
            child: Opacity(
              opacity: 0.72,
              child: Image.asset(
                headerAsset,
                fit: BoxFit.contain,
                errorBuilder: (_, _, _) => const _HeaderImageFallback(),
              ),
            ),
          ),
          Positioned(
            left: 0,
            right: 0,
            top: 14 * scale,
            child: Row(
              children: [
                SizedBox(
                  width: 166 * scale,
                  height: 64 * scale,
                  child: Image.asset(
                    logoAsset,
                    fit: BoxFit.contain,
                    alignment: Alignment.centerLeft,
                    errorBuilder: (_, _, _) => const _LogoFallback(),
                  ),
                ),
                const Spacer(),
                const _NotificationButton(),
                SizedBox(width: 10 * scale),
                const _ProfileAvatar(),
              ],
            ),
          ),
          Positioned(
            left: 0,
            right: 170 * scale,
            top: 116 * scale,
            child: Text(
              plan.title,
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                color: _PlannerColors.deepPurple,
                fontSize: 31 * scale,
                fontWeight: FontWeight.w900,
                height: 1.08,
              ),
            ),
          ),
          Positioned(
            left: 0,
            right: 180 * scale,
            top: 186 * scale,
            child: Text(
              'Crowd-aware itinerary',
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                color: _PlannerColors.textSub,
                fontSize: 17 * scale,
                fontWeight: FontWeight.w500,
                height: 1.25,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _NotificationButton extends StatelessWidget {
  const _NotificationButton();

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 42,
      height: 42,
      child: Stack(
        alignment: Alignment.center,
        children: [
          const Icon(
            Icons.notifications_none_rounded,
            color: _PlannerColors.deepPurple,
            size: 32,
          ),
          Positioned(
            top: 6,
            right: 8,
            child: Container(
              width: 8,
              height: 8,
              decoration: const BoxDecoration(
                color: _PlannerColors.lime,
                shape: BoxShape.circle,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ProfileAvatar extends StatelessWidget {
  const _ProfileAvatar();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 42,
      height: 42,
      decoration: BoxDecoration(
        color: _PlannerColors.lavender,
        shape: BoxShape.circle,
        border: Border.all(color: _PlannerColors.border),
        boxShadow: [
          BoxShadow(
            color: _PlannerColors.shadow.withValues(alpha: 0.12),
            blurRadius: 12,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: const Icon(
        Icons.person_rounded,
        color: _PlannerColors.purple,
        size: 26,
      ),
    );
  }
}

class _ControlsRow extends StatelessWidget {
  const _ControlsRow({
    required this.dateLabel,
    required this.scale,
    required this.onWhyPressed,
  });

  final String dateLabel;
  final double scale;
  final VoidCallback onWhyPressed;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: _DateSelector(dateLabel: dateLabel, scale: scale),
        ),
        SizedBox(width: 12 * scale),
        SizedBox(
          width: 158 * scale,
          child: _WhyRouteButton(scale: scale, onPressed: onWhyPressed),
        ),
      ],
    );
  }
}

class _DateSelector extends StatelessWidget {
  const _DateSelector({required this.dateLabel, required this.scale});

  final String dateLabel;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 48 * scale,
      padding: EdgeInsets.symmetric(horizontal: 12 * scale),
      decoration: _softCardDecoration(),
      child: Row(
        children: [
          Icon(
            Icons.chevron_left_rounded,
            color: _PlannerColors.textSub,
            size: 28 * scale,
          ),
          SizedBox(width: 6 * scale),
          Icon(
            Icons.calendar_month_rounded,
            color: _PlannerColors.textSub,
            size: 24 * scale,
          ),
          SizedBox(width: 10 * scale),
          Expanded(
            child: Text(
              dateLabel,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                color: _PlannerColors.textMain,
                fontSize: 17 * scale,
                fontWeight: FontWeight.w800,
                height: 1,
              ),
            ),
          ),
          Icon(
            Icons.keyboard_arrow_down_rounded,
            color: _PlannerColors.textSub,
            size: 22 * scale,
          ),
        ],
      ),
    );
  }
}

class _WhyRouteButton extends StatelessWidget {
  const _WhyRouteButton({required this.scale, required this.onPressed});

  final double scale;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 48 * scale,
      child: OutlinedButton.icon(
        key: const ValueKey('whyThisRouteButton'),
        onPressed: onPressed,
        icon: Icon(Icons.auto_awesome_rounded, size: 20 * scale),
        label: FittedBox(
          fit: BoxFit.scaleDown,
          child: Text(
            'Why this route?',
            style: TextStyle(fontSize: 15 * scale, fontWeight: FontWeight.w800),
          ),
        ),
        style: OutlinedButton.styleFrom(
          foregroundColor: _PlannerColors.purple,
          side: const BorderSide(color: _PlannerColors.purple, width: 1.2),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          padding: EdgeInsets.symmetric(horizontal: 10 * scale),
        ),
      ),
    );
  }
}

class _TimeChipRow extends StatelessWidget {
  const _TimeChipRow({
    required this.times,
    required this.selectedIndex,
    required this.scale,
    required this.onSelected,
  });

  final List<String> times;
  final int selectedIndex;
  final double scale;
  final ValueChanged<int> onSelected;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 46 * scale,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        physics: const BouncingScrollPhysics(),
        itemCount: times.length,
        separatorBuilder: (_, _) => SizedBox(width: 10 * scale),
        itemBuilder: (context, index) {
          final selected = index == selectedIndex;
          final time = times[index];

          return InkWell(
            key: ValueKey(selected ? 'selected-time-$time' : 'time-$time'),
            borderRadius: BorderRadius.circular(8),
            onTap: () => onSelected(index),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 170),
              width: 72 * scale,
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: selected ? null : _PlannerColors.white,
                borderRadius: BorderRadius.circular(8),
                border: selected
                    ? null
                    : Border.all(color: _PlannerColors.border),
                gradient: selected
                    ? const LinearGradient(
                        colors: [
                          _PlannerColors.purple,
                          _PlannerColors.purpleDark,
                        ],
                      )
                    : null,
                boxShadow: [
                  BoxShadow(
                    color: _PlannerColors.shadow.withValues(alpha: 0.08),
                    blurRadius: 12,
                    offset: const Offset(0, 6),
                  ),
                ],
              ),
              child: Text(
                time,
                style: TextStyle(
                  color: selected
                      ? _PlannerColors.white
                      : _PlannerColors.textSub,
                  fontSize: 18 * scale,
                  fontWeight: FontWeight.w800,
                  height: 1,
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}

class _ItineraryTimeline extends StatelessWidget {
  const _ItineraryTimeline({required this.items, required this.scale});

  final List<ItineraryItem> items;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: List.generate(items.length, (index) {
        return Padding(
          padding: EdgeInsets.only(bottom: index == items.length - 1 ? 0 : 10),
          child: _ItineraryCard(
            item: items[index],
            isFirst: index == 0,
            isLast: index == items.length - 1,
            scale: scale,
          ),
        );
      }),
    );
  }
}

class _ItineraryCard extends StatelessWidget {
  const _ItineraryCard({
    required this.item,
    required this.isFirst,
    required this.isLast,
    required this.scale,
  });

  final ItineraryItem item;
  final bool isFirst;
  final bool isLast;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final compact = constraints.maxWidth < 470;

        return Stack(
          children: [
            Positioned(
              left: 27 * scale,
              top: isFirst ? 48 * scale : 0,
              bottom: isLast ? 48 * scale : 0,
              child: Container(
                width: 2,
                decoration: BoxDecoration(
                  color: _PlannerColors.timelineLine,
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
            Container(
              padding: EdgeInsets.all(10 * scale),
              decoration: _softCardDecoration(),
              child: compact
                  ? _CompactItineraryContent(item: item, scale: scale)
                  : _WideItineraryContent(item: item, scale: scale),
            ),
          ],
        );
      },
    );
  }
}

class _WideItineraryContent extends StatelessWidget {
  const _WideItineraryContent({required this.item, required this.scale});

  final ItineraryItem item;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        _OrderCircle(order: item.order, scale: scale),
        SizedBox(width: 8 * scale),
        SizedBox(
          width: 50 * scale,
          child: Text(
            item.time,
            maxLines: 1,
            style: TextStyle(
              color: _PlannerColors.purple,
              fontSize: 16 * scale,
              fontWeight: FontWeight.w900,
            ),
          ),
        ),
        SizedBox(width: 8 * scale),
        _PlaceThumbnail(item: item, scale: scale),
        SizedBox(width: 10 * scale),
        Expanded(
          child: _ItineraryDetails(item: item, scale: scale),
        ),
        SizedBox(width: 8 * scale),
        _TipBox(text: item.aiTip, scale: scale),
      ],
    );
  }
}

class _CompactItineraryContent extends StatelessWidget {
  const _CompactItineraryContent({required this.item, required this.scale});

  final ItineraryItem item;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Row(
          children: [
            _OrderCircle(order: item.order, scale: scale),
            SizedBox(width: 8 * scale),
            SizedBox(
              width: 48 * scale,
              child: Text(
                item.time,
                style: TextStyle(
                  color: _PlannerColors.purple,
                  fontSize: 16 * scale,
                  fontWeight: FontWeight.w900,
                ),
              ),
            ),
            SizedBox(width: 8 * scale),
            _PlaceThumbnail(item: item, scale: scale),
            SizedBox(width: 10 * scale),
            Expanded(
              child: _ItineraryDetails(item: item, scale: scale),
            ),
          ],
        ),
        SizedBox(height: 8 * scale),
        Align(
          alignment: Alignment.centerRight,
          child: _TipBox(text: item.aiTip, scale: scale, wide: true),
        ),
      ],
    );
  }
}

class _OrderCircle extends StatelessWidget {
  const _OrderCircle({required this.order, required this.scale});

  final int order;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 34 * scale,
      height: 34 * scale,
      alignment: Alignment.center,
      decoration: const BoxDecoration(
        color: _PlannerColors.lavender,
        shape: BoxShape.circle,
      ),
      child: Text(
        '$order',
        style: TextStyle(
          color: _PlannerColors.deepPurple,
          fontSize: 16 * scale,
          fontWeight: FontWeight.w900,
          height: 1,
        ),
      ),
    );
  }
}

class _PlaceThumbnail extends StatelessWidget {
  const _PlaceThumbnail({required this.item, required this.scale});

  final ItineraryItem item;
  final double scale;

  @override
  Widget build(BuildContext context) {
    final assetPath = item.imageAssetPath;

    return ClipRRect(
      borderRadius: BorderRadius.circular(8),
      child: SizedBox(
        width: 82 * scale,
        height: 56 * scale,
        child: assetPath == null
            ? _PlaceImagePlaceholder(item: item)
            : Image.asset(
                assetPath,
                fit: BoxFit.cover,
                errorBuilder: (_, _, _) => _PlaceImagePlaceholder(item: item),
              ),
      ),
    );
  }
}

class _PlaceImagePlaceholder extends StatelessWidget {
  const _PlaceImagePlaceholder({required this.item});

  final ItineraryItem item;

  @override
  Widget build(BuildContext context) {
    final isLow = item.crowdLevel == ItineraryCrowdLevel.low;

    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: isLow
              ? const [Color(0xFFE9F9E6), Color(0xFFD9EEFF)]
              : const [Color(0xFFEAF2FF), Color(0xFFE7DCFF)],
        ),
      ),
      alignment: Alignment.center,
      child: const Icon(
        Icons.landscape_rounded,
        color: _PlannerColors.purple,
        size: 26,
      ),
    );
  }
}

class _ItineraryDetails extends StatelessWidget {
  const _ItineraryDetails({required this.item, required this.scale});

  final ItineraryItem item;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text(
          item.placeName,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: TextStyle(
            color: _PlannerColors.deepPurple,
            fontSize: 16 * scale,
            fontWeight: FontWeight.w900,
            height: 1.1,
          ),
        ),
        SizedBox(height: 8 * scale),
        Wrap(
          spacing: 8 * scale,
          runSpacing: 6 * scale,
          crossAxisAlignment: WrapCrossAlignment.center,
          children: [
            _CrowdBadge(level: item.crowdLevel, label: item.crowdLabel),
            _StayBadge(text: item.stayTime),
            if (item.extraBadge != null) _ExtraBadge(text: item.extraBadge!),
          ],
        ),
      ],
    );
  }
}

class _CrowdBadge extends StatelessWidget {
  const _CrowdBadge({required this.level, required this.label});

  final ItineraryCrowdLevel level;
  final String label;

  @override
  Widget build(BuildContext context) {
    final isLow = level == ItineraryCrowdLevel.low;

    return Container(
      height: 24,
      padding: const EdgeInsets.symmetric(horizontal: 9),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: isLow ? _PlannerColors.lowCrowdBg : _PlannerColors.moderateBg,
        borderRadius: BorderRadius.circular(8),
      ),
      child: FittedBox(
        fit: BoxFit.scaleDown,
        child: Text(
          label,
          style: TextStyle(
            color: isLow
                ? _PlannerColors.lowCrowdText
                : _PlannerColors.moderateText,
            fontSize: 12,
            fontWeight: FontWeight.w800,
            height: 1,
          ),
        ),
      ),
    );
  }
}

class _StayBadge extends StatelessWidget {
  const _StayBadge({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 24,
      child: FittedBox(
        fit: BoxFit.scaleDown,
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.schedule_rounded,
              color: _PlannerColors.textSub,
              size: 17,
            ),
            const SizedBox(width: 4),
            Text(
              text,
              style: const TextStyle(
                color: _PlannerColors.textSub,
                fontSize: 12,
                fontWeight: FontWeight.w600,
                height: 1,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ExtraBadge extends StatelessWidget {
  const _ExtraBadge({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 24,
      padding: const EdgeInsets.symmetric(horizontal: 8),
      decoration: BoxDecoration(
        color: _PlannerColors.sunsetBg,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: _PlannerColors.sunsetBorder),
      ),
      child: FittedBox(
        fit: BoxFit.scaleDown,
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.wb_sunny_outlined,
              color: _PlannerColors.sunsetText,
              size: 14,
            ),
            const SizedBox(width: 4),
            Text(
              text,
              style: const TextStyle(
                color: _PlannerColors.sunsetText,
                fontSize: 12,
                fontWeight: FontWeight.w700,
                height: 1,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _TipBox extends StatelessWidget {
  const _TipBox({required this.text, required this.scale, this.wide = false});

  final String text;
  final double scale;
  final bool wide;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: wide ? double.infinity : 94 * scale,
      constraints: BoxConstraints(minHeight: 58 * scale),
      padding: EdgeInsets.symmetric(horizontal: 8 * scale, vertical: 8 * scale),
      decoration: BoxDecoration(
        color: _PlannerColors.tipBg,
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisSize: wide ? MainAxisSize.max : MainAxisSize.min,
        children: [
          Icon(
            Icons.auto_awesome_rounded,
            color: _PlannerColors.purple,
            size: 15 * scale,
          ),
          SizedBox(width: 5 * scale),
          Expanded(
            child: Text(
              text,
              maxLines: 3,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                color: _PlannerColors.textSub,
                fontSize: 11.5 * scale,
                fontWeight: FontWeight.w500,
                height: 1.28,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _RouteSummaryCard extends StatelessWidget {
  const _RouteSummaryCard({required this.plan, required this.scale});

  final ItineraryPlan plan;
  final double scale;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final compact = constraints.maxWidth < 390;

        final text = Row(
          children: [
            Container(
              width: 52 * scale,
              height: 52 * scale,
              decoration: const BoxDecoration(
                color: _PlannerColors.lavender,
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.auto_graph_rounded,
                color: _PlannerColors.purple,
                size: 30 * scale,
              ),
            ),
            SizedBox(width: 12 * scale),
            Expanded(
              child: Text.rich(
                TextSpan(
                  children: [
                    const TextSpan(text: "You'll save up to "),
                    TextSpan(
                      text: '${plan.estimatedTimeSaved}\n',
                      style: const TextStyle(color: _PlannerColors.purple),
                    ),
                    const TextSpan(text: 'compared to a typical route!'),
                  ],
                ),
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(
                  color: _PlannerColors.deepPurple,
                  fontSize: 16 * scale,
                  fontWeight: FontWeight.w800,
                  height: 1.24,
                ),
              ),
            ),
          ],
        );

        const map = _RouteOverviewMiniMap();

        return Container(
          padding: EdgeInsets.all(12 * scale),
          decoration: BoxDecoration(
            gradient: const LinearGradient(
              colors: [_PlannerColors.summaryBg, _PlannerColors.white],
            ),
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: _PlannerColors.border),
            boxShadow: _cardShadow(),
          ),
          child: compact
              ? Column(
                  children: [
                    text,
                    SizedBox(height: 10 * scale),
                    SizedBox(height: 74 * scale, child: map),
                  ],
                )
              : Row(
                  children: [
                    Expanded(child: text),
                    SizedBox(width: 12 * scale),
                    SizedBox(
                      width: 170 * scale,
                      height: 64 * scale,
                      child: map,
                    ),
                  ],
                ),
        );
      },
    );
  }
}

class _RouteOverviewMiniMap extends StatelessWidget {
  const _RouteOverviewMiniMap();

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(8),
      child: CustomPaint(
        painter: _RouteOverviewPainter(),
        child: const SizedBox.expand(),
      ),
    );
  }
}

class _SavePlanButton extends StatelessWidget {
  const _SavePlanButton({
    required this.isSaving,
    required this.scale,
    required this.onPressed,
  });

  final bool isSaving;
  final double scale;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 58 * scale,
      child: DecoratedBox(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8),
          gradient: const LinearGradient(
            colors: [_PlannerColors.purple, _PlannerColors.purpleDark],
          ),
          boxShadow: [
            BoxShadow(
              color: _PlannerColors.purple.withValues(alpha: 0.24),
              blurRadius: 16,
              offset: const Offset(0, 8),
            ),
          ],
        ),
        child: FilledButton.icon(
          key: const ValueKey('savePlanButton'),
          onPressed: isSaving ? null : onPressed,
          icon: isSaving
              ? const SizedBox(
                  width: 22,
                  height: 22,
                  child: CircularProgressIndicator(
                    strokeWidth: 2.4,
                    color: _PlannerColors.white,
                  ),
                )
              : Icon(Icons.bookmark_border_rounded, size: 28 * scale),
          label: Text(
            isSaving ? 'Saving...' : 'Save this plan',
            style: TextStyle(fontSize: 21 * scale, fontWeight: FontWeight.w900),
          ),
          style: FilledButton.styleFrom(
            foregroundColor: _PlannerColors.white,
            backgroundColor: Colors.transparent,
            disabledBackgroundColor: Colors.transparent,
            shadowColor: Colors.transparent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
      ),
    );
  }
}

class _BottomNavigation extends StatelessWidget {
  const _BottomNavigation({
    required this.selectedIndex,
    required this.scale,
    required this.height,
    required this.safeBottom,
    required this.onChanged,
  });

  final int selectedIndex;
  final double scale;
  final double height;
  final double safeBottom;
  final ValueChanged<int> onChanged;

  @override
  Widget build(BuildContext context) {
    const items = [
      _BottomNavData('Home', Icons.home_outlined),
      _BottomNavData('Itinerary', Icons.calendar_month_rounded),
      _BottomNavData('Scan', Icons.crop_free_rounded),
      _BottomNavData('Discover', Icons.explore_outlined),
      _BottomNavData('My', Icons.person_outline_rounded),
    ];

    return Container(
      height: height,
      decoration: BoxDecoration(
        color: _PlannerColors.white,
        border: const Border(top: BorderSide(color: _PlannerColors.border)),
        boxShadow: [
          BoxShadow(
            color: _PlannerColors.shadow.withValues(alpha: 0.12),
            blurRadius: 18,
            offset: const Offset(0, -6),
          ),
        ],
      ),
      child: Padding(
        padding: EdgeInsets.only(top: 6 * scale, bottom: safeBottom),
        child: Row(
          children: List.generate(items.length, (index) {
            final data = items[index];
            final selected = index == selectedIndex;
            final isScan = index == 2;

            return Expanded(
              child: InkWell(
                onTap: () => onChanged(index),
                child: Transform.translate(
                  offset: Offset(0, isScan ? -10 * scale : 0),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      if (!isScan)
                        AnimatedContainer(
                          duration: const Duration(milliseconds: 160),
                          width: selected ? 54 * scale : 0,
                          height: 3,
                          margin: EdgeInsets.only(bottom: 7 * scale),
                          decoration: BoxDecoration(
                            color: selected
                                ? _PlannerColors.purple
                                : Colors.transparent,
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      Container(
                        width: isScan ? 52 * scale : null,
                        height: isScan ? 52 * scale : null,
                        decoration: isScan
                            ? BoxDecoration(
                                color: _PlannerColors.white,
                                shape: BoxShape.circle,
                                boxShadow: _cardShadow(),
                              )
                            : null,
                        child: Icon(
                          data.icon,
                          color: selected
                              ? _PlannerColors.purple
                              : _PlannerColors.navMuted,
                          size: (isScan ? 28 : 26) * scale,
                        ),
                      ),
                      SizedBox(height: 4 * scale),
                      Text(
                        data.label,
                        style: TextStyle(
                          color: selected
                              ? _PlannerColors.purple
                              : _PlannerColors.navMuted,
                          fontSize: 11.5 * scale,
                          fontWeight: selected
                              ? FontWeight.w800
                              : FontWeight.w500,
                          height: 1,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          }),
        ),
      ),
    );
  }
}

class _HeaderImageFallback extends StatelessWidget {
  const _HeaderImageFallback();

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: _PlannerColors.lavender,
        borderRadius: BorderRadius.all(Radius.circular(8)),
      ),
      child: const Icon(
        Icons.account_balance_rounded,
        color: _PlannerColors.purple,
        size: 46,
      ),
    );
  }
}

class _LogoFallback extends StatelessWidget {
  const _LogoFallback();

  @override
  Widget build(BuildContext context) {
    return const FittedBox(
      alignment: Alignment.centerLeft,
      fit: BoxFit.contain,
      child: Text.rich(
        TextSpan(
          children: [
            TextSpan(text: 'Nori'),
            TextSpan(
              text: 'Go',
              style: TextStyle(color: _PlannerColors.lime),
            ),
          ],
        ),
        style: TextStyle(
          color: _PlannerColors.deepPurple,
          fontSize: 44,
          fontWeight: FontWeight.w900,
          height: 1,
        ),
      ),
    );
  }
}

class _ErrorState extends StatelessWidget {
  const _ErrorState({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              message,
              textAlign: TextAlign.center,
              style: const TextStyle(
                color: _PlannerColors.deepPurple,
                fontSize: 16,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 12),
            FilledButton(onPressed: onRetry, child: const Text('Try again')),
          ],
        ),
      ),
    );
  }
}

class _RouteOverviewPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final w = size.width;
    final h = size.height;

    canvas.drawRect(
      Offset.zero & size,
      Paint()..color = const Color(0xFFF3F6F0),
    );

    final roadPaint = Paint()
      ..color = _PlannerColors.white
      ..strokeWidth = 5
      ..strokeCap = StrokeCap.round;

    for (var i = 0; i < 6; i++) {
      final y = h * (0.16 + i * 0.14);
      canvas.drawLine(Offset(0, y), Offset(w, y + math.sin(i) * 10), roadPaint);
    }

    for (var i = 0; i < 5; i++) {
      final x = w * (0.14 + i * 0.20);
      canvas.drawLine(Offset(x, 0), Offset(x + math.cos(i) * 10, h), roadPaint);
    }

    canvas.drawOval(
      Rect.fromLTWH(w * 0.74, -h * 0.18, w * 0.30, h * 0.56),
      Paint()..color = const Color(0xFFC9ECC8).withValues(alpha: 0.78),
    );
    canvas.drawOval(
      Rect.fromLTWH(w * 0.80, h * 0.48, w * 0.35, h * 0.58),
      Paint()..color = const Color(0xFFCFE8FA).withValues(alpha: 0.82),
    );

    final route = Path()
      ..moveTo(w * 0.18, h * 0.26)
      ..cubicTo(w * 0.32, h * 0.10, w * 0.44, h * 0.46, w * 0.57, h * 0.36)
      ..cubicTo(w * 0.75, h * 0.23, w * 0.73, h * 0.72, w * 0.88, h * 0.54);

    _drawDashedPath(
      canvas,
      route,
      Paint()
        ..color = _PlannerColors.purple
        ..strokeWidth = 2.6
        ..style = PaintingStyle.stroke
        ..strokeCap = StrokeCap.round,
    );

    final points = [
      Offset(w * 0.18, h * 0.26),
      Offset(w * 0.40, h * 0.38),
      Offset(w * 0.57, h * 0.36),
      Offset(w * 0.30, h * 0.72),
      Offset(w * 0.88, h * 0.54),
    ];

    for (var i = 0; i < points.length; i++) {
      canvas.drawCircle(points[i], 12, Paint()..color = _PlannerColors.purple);
      final painter = TextPainter(
        text: TextSpan(
          text: '${i + 1}',
          style: const TextStyle(
            color: _PlannerColors.white,
            fontSize: 11,
            fontWeight: FontWeight.w900,
          ),
        ),
        textDirection: TextDirection.ltr,
      )..layout();

      painter.paint(
        canvas,
        Offset(
          points[i].dx - painter.width / 2,
          points[i].dy - painter.height / 2,
        ),
      );
    }
  }

  void _drawDashedPath(Canvas canvas, Path path, Paint paint) {
    for (final metric in path.computeMetrics()) {
      var distance = 0.0;
      const dashLength = 7.0;
      const dashGap = 5.0;

      while (distance < metric.length) {
        final next = math.min(distance + dashLength, metric.length);
        canvas.drawPath(metric.extractPath(distance, next), paint);
        distance = next + dashGap;
      }
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

class _BottomNavData {
  const _BottomNavData(this.label, this.icon);

  final String label;
  final IconData icon;
}

class _PlannerColors {
  const _PlannerColors._();

  static const white = Color(0xFFFFFFFF);
  static const deepPurple = Color(0xFF24104F);
  static const purple = Color(0xFF6A00FF);
  static const purpleDark = Color(0xFF4A12E6);
  static const lime = Color(0xFFCCFF00);

  static const textMain = Color(0xFF41465F);
  static const textSub = Color(0xFF616783);
  static const navMuted = Color(0xFF747A91);

  static const border = Color(0xFFE5E1EE);
  static const timelineLine = Color(0xFFDADDE6);
  static const shadow = Color(0xFF6F668D);

  static const lavender = Color(0xFFF3EDFF);
  static const tipBg = Color(0xFFF6F2FF);
  static const summaryBg = Color(0xFFF3ECFF);

  static const lowCrowdBg = Color(0xFFDDF7D7);
  static const lowCrowdText = Color(0xFF1C7B27);
  static const moderateBg = Color(0xFFE0EFFF);
  static const moderateText = Color(0xFF196CE8);

  static const sunsetBg = Color(0xFFFFF5E8);
  static const sunsetBorder = Color(0xFFFFC885);
  static const sunsetText = Color(0xFFFF7A00);
}

BoxDecoration _softCardDecoration() {
  return BoxDecoration(
    color: _PlannerColors.white,
    borderRadius: BorderRadius.circular(8),
    border: Border.all(color: _PlannerColors.border),
    boxShadow: _cardShadow(),
  );
}

List<BoxShadow> _cardShadow() {
  return [
    BoxShadow(
      color: _PlannerColors.shadow.withValues(alpha: 0.08),
      blurRadius: 18,
      offset: const Offset(0, 8),
    ),
  ];
}
