import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:norigo/core/services/supabase_config.dart';
import 'package:norigo/features/ennoia/data/ennoia_agent_repository.dart';
import 'package:norigo/features/ennoia/domain/culture_guide_result.dart';
import 'package:norigo/features/ennoia/domain/itinerary_agent_result.dart';
import 'package:norigo/features/ennoia/domain/retrip_agent_result.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SupabaseEnnoiaAgentRepository implements EnnoiaAgentRepository {
  const SupabaseEnnoiaAgentRepository({
    this.config = const SupabaseConfig(),
    http.Client? client,
  }) : _client = client;

  final SupabaseConfig config;
  final http.Client? _client;

  static const _persistedSourceType = 'ennoia_kto_mcp';
  static const _sourceNote =
      'Generated by ennoia Agent through Supabase Edge Functions with KTO MCP context.';

  @override
  Future<CultureGuideResult> fetchCultureGuide(
    CultureGuideAgentRequest request,
  ) async {
    final payload = await _invokeFunction(
      'ennoia-culture-guide',
      request.toJson(),
      listKey: 'items',
    );
    return CultureGuideResult.fromJson(payload);
  }

  @override
  Future<ItineraryAgentResult> fetchItinerary(
    ItineraryAgentRequest request,
  ) async {
    final payload = await _invokeFunction(
      'ennoia-itinerary',
      request.toJson(),
      listKey: 'items',
    );
    return ItineraryAgentResult.fromJson(payload);
  }

  @override
  Future<ItineraryAgentResult> generateItinerary(
    ItineraryAgentRequest request,
  ) {
    return fetchItinerary(request);
  }

  @override
  Future<RetripAgentResult> fetchRetrip(RetripAgentRequest request) async {
    final payload = await _invokeFunction(
      'ennoia-retrip',
      request.toJson(),
      listKey: 'alternatives',
    );
    return RetripAgentResult.fromJson(payload);
  }

  @override
  Future<void> saveCultureScanRecord(
    CultureGuideAgentRequest request,
    CultureGuideResult result,
  ) async {
    await _insertRow('culture_scan_records', {
      'user_language': request.userLanguage,
      'current_location': request.currentLocation,
      'detected_object': result.detectedObject,
      'korean_keyword': result.koreanSource,
      'question': result.question,
      'description': result.description,
      'meaning': result.meaning,
      'etiquette': result.etiquette,
      'story': result.story,
      'korean_phrase': result.koreanPhrase,
      'pronunciation': result.pronunciation,
      'phrase_meaning': result.phraseMeaning,
      'confidence': result.confidence,
      'source_note': result.sourceNote ?? _sourceNote,
      'source_type': _persistedSourceType,
    });
  }

  @override
  Future<void> saveItineraryPlan(
    ItineraryAgentRequest request,
    ItineraryAgentResult result,
  ) async {
    await _insertRow('itinerary_plans', {
      'date_label': result.dateLabel,
      'summary': result.title,
      'time_saved': result.estimatedTimeSaved,
      'source_note': result.sourceNote ?? _sourceNote,
      'raw_json': {'request': request.toJson(), 'result': result.toJson()},
      'source_type': result.sourceType,
    });
  }

  @override
  Future<void> saveReTripEvent(
    RetripAgentRequest request,
    RetripAgentResult result,
  ) async {
    await _insertRow('retrip_events', {
      'original_place': result.originalPlace,
      'trigger_type': request.triggerType,
      'crowd_level': result.crowdLevel,
      'estimated_wait': result.estimatedWait,
      'recommended_action': result.recommendedAction,
      'source_note': result.sourceNote ?? _sourceNote,
      'raw_json': {'request': request.toJson(), 'result': result.toJson()},
      'source_type': _persistedSourceType,
    });
  }

  Future<Map<String, Object?>> _invokeFunction(
    String functionName,
    Map<String, Object?> body, {
    required String listKey,
  }) async {
    if (!config.isConfigured) {
      throw const EnnoiaAgentException('Supabase is not configured.');
    }

    final response = await _post(_functionUri(functionName), body).timeout(
      const Duration(seconds: 24),
      onTimeout: () =>
          throw const EnnoiaAgentException('Supabase Edge Function timed out.'),
    );

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw EnnoiaAgentException(
        _responseErrorMessage(
          response.body,
          'Supabase Edge Function failed with status ${response.statusCode}.',
        ),
      );
    }

    final decoded = jsonDecode(response.body);
    return _extractAgentPayload(decoded, listKey: listKey);
  }

  Future<void> _insertRow(String tableName, Map<String, Object?> values) async {
    if (!config.isConfigured) {
      throw const EnnoiaAgentException('Supabase is not configured.');
    }

    final response =
        await _post(
          _restUri(tableName),
          _withoutNullValues(values),
          extraHeaders: const {'Prefer': 'return=minimal'},
        ).timeout(
          const Duration(seconds: 12),
          onTimeout: () =>
              throw const EnnoiaAgentException('Supabase insert timed out.'),
        );

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw EnnoiaAgentException(
        _responseErrorMessage(
          response.body,
          'Supabase insert failed with status ${response.statusCode}.',
        ),
      );
    }
  }

  Uri _functionUri(String functionName) {
    return Uri.parse('${_baseUrl()}/functions/v1/$functionName');
  }

  Uri _restUri(String tableName) {
    return Uri.parse('${_baseUrl()}/rest/v1/$tableName');
  }

  String _baseUrl() {
    return config.url.replaceAll(RegExp(r'/+$'), '');
  }

  Future<http.Response> _post(
    Uri uri,
    Map<String, Object?> body, {
    Map<String, String> extraHeaders = const {},
  }) {
    final bearerToken = _bearerToken();
    final headers = {
      'Authorization': 'Bearer $bearerToken',
      'apikey': config.anonKey,
      'Content-Type': 'application/json; charset=utf-8',
      ...extraHeaders,
    };
    final encodedBody = jsonEncode(body);

    final client = _client;
    if (client != null) {
      return client.post(uri, headers: headers, body: encodedBody);
    }
    return http.post(uri, headers: headers, body: encodedBody);
  }

  String _bearerToken() {
    try {
      final accessToken =
          Supabase.instance.client.auth.currentSession?.accessToken;
      if (accessToken != null && accessToken.isNotEmpty) {
        return accessToken;
      }
    } catch (_) {
      // Supabase is optional in mock-first demos; fall back to anon key.
    }

    return config.anonKey;
  }

  Map<String, Object?> _withoutNullValues(Map<String, Object?> values) {
    return Map.fromEntries(
      values.entries.where((entry) => entry.value != null),
    );
  }

  Map<String, Object?> _extractAgentPayload(
    Object? decoded, {
    required String listKey,
  }) {
    final payload = _extractOpenAiContent(decoded) ?? decoded;
    final parsed = payload is String ? _parseContentString(payload) : payload;

    if (parsed is Map<String, Object?>) return parsed;
    if (parsed is Map) return Map<String, Object?>.from(parsed);
    if (parsed is List) return {listKey: parsed};

    throw const EnnoiaAgentException('ennoia response was not valid JSON.');
  }

  Object? _extractOpenAiContent(Object? decoded) {
    if (decoded is! Map) return null;
    final choices = decoded['choices'];
    if (choices is! List || choices.isEmpty) return null;

    final firstChoice = choices.first;
    if (firstChoice is! Map) return null;

    final message = firstChoice['message'];
    if (message is Map && message['content'] is String) {
      return message['content'];
    }
    if (firstChoice['text'] is String) return firstChoice['text'];
    return null;
  }

  Object? _parseContentString(String content) {
    final trimmed = content.trim();
    if (trimmed.isEmpty) {
      throw const EnnoiaAgentException('ennoia returned empty content.');
    }

    try {
      return jsonDecode(trimmed);
    } on FormatException {
      final jsonLike = _extractJsonLikeText(trimmed);
      if (jsonLike == null) rethrow;
      return jsonDecode(jsonLike);
    }
  }

  String? _extractJsonLikeText(String content) {
    final objectStart = content.indexOf('{');
    final objectEnd = content.lastIndexOf('}');
    final arrayStart = content.indexOf('[');
    final arrayEnd = content.lastIndexOf(']');

    final hasObject = objectStart != -1 && objectEnd > objectStart;
    final hasArray = arrayStart != -1 && arrayEnd > arrayStart;

    if (hasObject && (!hasArray || objectStart < arrayStart)) {
      return content.substring(objectStart, objectEnd + 1);
    }
    if (hasArray) {
      return content.substring(arrayStart, arrayEnd + 1);
    }
    return null;
  }

  String _responseErrorMessage(String body, String fallback) {
    if (body.trim().isEmpty) return fallback;

    try {
      final decoded = jsonDecode(body);
      if (decoded is Map) {
        final detail = decoded['detail'];
        if (detail is Map) {
          final detailMessage = detail['message'];
          if (detailMessage is String && detailMessage.trim().isNotEmpty) {
            return detailMessage.trim();
          }
        }

        final message = decoded['error'] ?? decoded['message'];
        if (message is String && message.trim().isNotEmpty) {
          return message.trim();
        }
      }
    } catch (_) {
      // Keep the stable fallback for non-JSON gateway errors.
    }

    return fallback;
  }
}

class EnnoiaAgentException implements Exception {
  const EnnoiaAgentException(this.message);

  final String message;

  @override
  String toString() => 'EnnoiaAgentException: $message';
}
